"""empty message

Revision ID: 3200e7e3a829
Revises: 4a2d6bcc2eb4
Create Date: 2024-12-11 09:34:46.223019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3200e7e3a829'
down_revision = '4a2d6bcc2eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('request_text', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('timestamps', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('request_id', name=op.f('pk_requests'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
