"""empty message

Revision ID: 3fb59c2e78f2
Revises: 350b0cfe3812
Create Date: 2024-12-18 11:40:18.665631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb59c2e78f2'
down_revision = '350b0cfe3812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('timestamps', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], name=op.f('fk_messages_post_id_posts')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.request_id'], name=op.f('fk_messages_request_id_requests')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_messages_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
