"""empty message

Revision ID: 9d1877705d63
Revises: 0233bf6a3a49
Create Date: 2024-12-18 10:45:23.566073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d1877705d63'
down_revision = '0233bf6a3a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('timestamps', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], name=op.f('fk_messages_post_id_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
