"""empty message

Revision ID: 9e8efd34972f
Revises: 5674cfb74230
Create Date: 2024-12-04 10:57:09.037093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8efd34972f'
down_revision = '5674cfb74230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('point', sa.Integer(), nullable=False))
    # pointカラムにデフォルト値を設定し、NOT NULL制約を付与
        batch_op.add_column(sa.Column('point', sa.Integer(), nullable=False, server_default="3"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('point')

    # ### end Alembic commands ###
