"""empty message

Revision ID: c67a17b70a4b
Revises: 9d1877705d63
Create Date: 2024-12-18 10:52:05.309352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67a17b70a4b'
down_revision = '9d1877705d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_messages_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_messages_request_id_requests'), 'requests', ['request_id'], ['request_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_request_id_requests'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_messages_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('request_id')

    # ### end Alembic commands ###
